# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='working.Workspace'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='working.Book'),
        ),
    ]
