# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0002_auto_20191106_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('blurb', models.TextField(blank=True, max_length=140)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='working.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('blurb', models.TextField(blank=True, max_length=140)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='working.Workspace')),
            ],
        ),
    ]
