# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0003_entry_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='shorthand',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
